/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan10;
import static pertemuan10.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Wahyu
 */
public class frmTeman extends javax.swing.JFrame {
    String edNama;
    DefaultTableModel TM = new DefaultTableModel();

    /**
     * Creates new form frmTeman
     */
    public frmTeman() throws SQLException{
        initComponents();
        
        tblTeman.setModel(TM);
        TM.addColumn("No");
        TM.addColumn("Nama Teman");
        TM.addColumn("Alamat");
        TM.addColumn("Telp");
        
        this.dtTemanList();
        fieldisEnabled(false);
        tombolisEnabled(false);
        btnTambah.setEnabled(true);
        btnTutup.setEnabled(true);
    }
    
    private void fieldisEnabled(boolean opsi){
        txNama.setEditable(opsi);
        txAlamat.setEditable(opsi);
        txTelp.setEditable(opsi);
    }
    
    private void tombolisEnabled(boolean opsi){
        btnTambah.setEnabled(opsi);
        btnUbah.setEnabled(opsi);
        btnHapus.setEnabled(opsi);
        btnTutup.setEnabled(opsi);
    }
    
    private void resetForm(){
        txNama.setText("");
        txAlamat.setText("");
        txTelp.setText("");
    }
    
//    CRUD
    private void storeData() throws SQLException{
        String namateman = txNama.getText();
        String alamat = txAlamat.getText();
        String telp = txTelp.getText();
        
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("INSERT INTO datateman(namateman, alamat, telp) VALUES(?,?,?);");
        PS.setString(1, namateman);
        PS.setString(2, alamat);
        PS.setString(3, telp);
        PS.executeUpdate();
    }
//    ubah data
    private void updateData()throws SQLException{
        String namateman = txNama.getText();
        String alamat = txAlamat.getText();
        String telp = txTelp.getText();
        
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("UPDATE datateman SET namateman=?, alamat=?, telp=? WHERE namateman=?;");
        PS.setString(1, namateman);
        PS.setString(2, alamat);
        PS.setString(3, telp);
        PS.setString(4, this.edNama);
        PS.executeUpdate();
    }
    private void destroyData()throws SQLException{
        String namateman = txNama.getText();
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("DELETE FROM datateman WHERE namateman=?;");
        PS.setString(1, namateman);
        PS.executeUpdate();
    }
            
    private void dtTemanList() throws SQLException{
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("SELECT * FROM datateman;");
        ResultSet RS = PS.executeQuery();
        
        TM.getDataVector().removeAllElements();
        TM.fireTableDataChanged();
        
        while(RS.next() ){
            Object[] dta = new Object[4];
                dta[0] = RS.getInt("idteman");
                dta[1] = RS.getString("namateman");
                dta[2] = RS.getString("alamat");
                dta[3] = RS.getString("telp");
            TM.addRow(dta);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txAlamat = new javax.swing.JTextField();
        txTelp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTeman = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Teman");
        setResizable(false);

        txNama.setName("txNama"); // NOI18N

        jLabel1.setText("Nama");

        jLabel2.setText("Alamat");

        txAlamat.setName("txAlamat"); // NOI18N

        txTelp.setName("txTelp"); // NOI18N

        jLabel3.setText("Telp");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Data Teman");

        tblTeman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Telp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTeman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTemanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTeman);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txNama)
                            .addComponent(txAlamat)
                            .addComponent(txTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnTambah)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus)
                            .addComponent(btnTutup))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnTutup)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTemanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTemanMouseClicked

         txNama.setText( tblTeman.getValueAt(tblTeman.getSelectedRow(), 1).toString());
         txAlamat.setText(tblTeman.getValueAt(tblTeman.getSelectedRow(), 2).toString());
         txTelp.setText(tblTeman.getValueAt(tblTeman.getSelectedRow(), 3).toString());
         btnUbah.setEnabled(true);
         btnHapus.setEnabled(true);
    }//GEN-LAST:event_tblTemanMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if(btnTambah.getText().equals("Tambah")){
            tombolisEnabled(false);
            btnTambah.setText("Simpan");
            btnTutup.setText("Batal");
            btnTambah.setEnabled(true);
            btnTutup.setEnabled(true);
            resetForm();
            fieldisEnabled(true);
        }else{
            btnTambah.setText("Tambah");
            btnTutup.setText("Tutup");
            try {
                storeData();
                dtTemanList();
            } catch (SQLException ex) {
                Logger.getLogger(frmTeman.class.getName()).log(Level.SEVERE, null, ex);
            }
            resetForm();
            fieldisEnabled(false);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        if (btnTutup.getText().equals("Tutup")){
            int jopsi = JOptionPane.showOptionDialog(this, 
                    "Yakin akan menutup aplikasi?", 
                    "Konfirmasi tutup aplikasi", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, 
                    null, null, null);
            if(jopsi==JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }else{
            resetForm();
            fieldisEnabled(false);
            btnTambah.setText("Tambah");
            btnTutup.setText("Tutup");
            btnUbah.setText("Ubah");
            btnTambah.setEnabled(true);
            btnUbah.setEnabled(false);
        }
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if(btnUbah.getText().equals("Ubah")){
            btnUbah.setText("Simpan");
            btnTutup.setText("Batal");
            tombolisEnabled(false);
            btnUbah.setEnabled(true);
            btnTutup.setEnabled(true);
            btnTutup.setEnabled(true);
            fieldisEnabled(true);
            this.edNama = txNama.getText();
        }else{
            try {
                updateData();
                dtTemanList();
            } catch (SQLException ex) {
                Logger.getLogger(frmTeman.class.getName()).log(Level.SEVERE, null, ex);
            }
            btnUbah.setText("Ubah");
            btnTutup.setText("Tutup");
            btnTambah.setEnabled(true);
            btnHapus.setEnabled(true);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String isNama = txNama.getText();
        int jopsi = JOptionPane.showOptionDialog(this,
                "Apakah yakin ingin menghapus data "+isNama+"?", 
                "Konfirmasi Hapus Data",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, 
                null, null, null);
        if(jopsi == JOptionPane.YES_OPTION){
            try {
                destroyData();
                dtTemanList();
                
                resetForm();
                btnUbah.setEnabled(false);
                btnHapus.setEnabled(false);
            } catch (SQLException ex) {
                Logger.getLogger(frmTeman.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmTeman().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmTeman.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTutup;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTeman;
    private javax.swing.JTextField txAlamat;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txTelp;
    // End of variables declaration//GEN-END:variables
}
